// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZe74IaT7n2woloynxDt5JuMi83VIhT0',
    appId: '1:849581185996:web:d80a7af86a757b2b2c5b69',
    messagingSenderId: '849581185996',
    projectId: 'chat-19e33',
    authDomain: 'chat-19e33.firebaseapp.com',
    storageBucket: 'chat-19e33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiUXQLNzhthTbVrSDhrDaTMQxhsxzn5Ao',
    appId: '1:849581185996:android:ff73c89afa07949d2c5b69',
    messagingSenderId: '849581185996',
    projectId: 'chat-19e33',
    storageBucket: 'chat-19e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYaAuGZe6i3R-C-1xN14hUEn2vSuYqRro',
    appId: '1:849581185996:ios:13c2acd36c79d00a2c5b69',
    messagingSenderId: '849581185996',
    projectId: 'chat-19e33',
    storageBucket: 'chat-19e33.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
